# License: CC0-1.0
general:
  name: ComnGood
  logo: "logos/ComnGoodLogo.png"
  logo_full: "logos/ComnGoodLogo.png"

default:
  image:
    profile: "/images/fallback/default-profile.png"
    nonprofit: "/images/fallback/default-nonprofit.png"
    campaign: "/fallback/default-campaign-background.jpg"


cache_store: dalli_store

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>

mailer:
  host: "http://localhost"
  default_from: "ComnGood Team <support@comngood.org>"
  email: "support@comngood.org"

cdn:
  url: <%= ENV['CDN_URL']  || 'http://localhost:5000' %>

payment_provider:
  stripe_connect: true
  stripe_public_key: <%= ENV['STRIPE_API_PUBLIC'] %>
  stripe_private_key: <%= ENV['STRIPE_API_KEY'] %>
  stripe_proprietary_v2_js: true

default_bp:
  id: 1

devise:
  mailer_sender: 'support@comngood.org'

page_editor:
  editor: 'quill'

language: 'en'
available_locales: ['en', 'es']

intntl:
  currencies: ["usd"]
  all_currencies:
    - unit: "dollars"
      subunit: "cents"
      symbol: "$"
      abbv: "usd"
      format: "%u%n"
    - unit: "euro"
      subunit: "cents"
      symbol: "€"
      abbv: "eur"
      format: "%n%u"

source_tokens:
  max_uses: 1
  expiration_time: 1200
  event_donation_source:
    time_after_event: 1728000
    max_uses: 20

nonprofits_must_be_vetted: false

api_domain:
  url: <%= ENV['API_DOMAIN_URL']  || 'http://localhost:5000' %>

